name: CI Check

on:
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:

    gradle-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Gradle Cache Setup
              uses: gradle/actions/setup-gradle@v3
            - name: Gradle Check
              run: ./gradlew check
