name: Rebase

on:
    push:
        branches: [main]

permissions:
    contents: write
    pull-requests: write

jobs:
    rebase:
        runs-on: ubuntu-latest
        steps:
            - uses: peter-evans/rebase@v3
              with:
                  base: main
